import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Login from '../components/Login'
import {useMoralis} from 'react-moralis'
export default function Home() {

  const{isAuthenticated, logout}= useMoralis();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
{
  isAuthenticated ? (
    <p>You are logged in
      <button onClick={logout}>Sign Out</button>
    </p>
    
  ): (
    <Login/>
  )
}

     <Login/>
    </div>
  )
}
